//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEN4020.TVTS.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public string VehicleId { get; set; }
        public string CustomerId { get; set; }
    }
}
